package est.shorturl;

public class UnknownURLException extends Exception {

    /**
     * Exception when for when the short link cannot be mapped to an URL
     * because it has not been generated by this application
     * @param url
     */
    public UnknownURLException(String url) {
        super("unknown URL: "+url);
    }
    
}
